apiVersion: infrastructure.flintlock.x-k8s.io/v1alpha1
kind: Microvm
metadata:
  labels:
    app.kubernetes.io/name: microvm
    app.kubernetes.io/instance: microvm-sample
    app.kubernetes.io/part-of: microvm-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: microvm-operator
  name: microvm-sample
spec:
  # TODO(user): Add fields here
